// import * as Popper from '@popperjs/core';
import {Carousel, Popover} from 'bootstrap';
import 'bs5-lightbox';
import '@fontsource/lato';
import '@fontsource-variable/eb-garamond';
import '@fontsource-variable/eb-garamond/wght-italic.css';
import './main.scss';
import './js/theme-picker.js';
import './js/rugby.js';
import './js/maps.js';
import './js/popovers.js';
